version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
    command: gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - ./apps/backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
    command: flutter run -d web-server --web-port 8080
    volumes:
      - ./apps/frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:
